### ISSUE TITLE
[missing icon] register.365

### ISSUE THREAD

**Issue by tamaswallner** [tommycarpi/sentinel-icons#12]
Register355.ie
![Uploading BA5B7900-D293-499B-ADF8-D486A8590686.png…]()

**Comment by tommycarpi** [comment]
It looks like the icon did not upload correctly.
I also tried to look for the website but does not exists ☺️

**Comment by tamaswallner** [comment]
No worries, thanks for your work

From: tommycarpi ***@***.***>
Date: Wednesday, 24 August 2022 at 14:59
To: tommycarpi/sentinel-icons ***@***.***>
Cc: Tamas Wallner ***@***.***>, Author ***@***.***>
Subject: Re: [tommycarpi/sentinel-icons] [missing icon] register.365 (Issue #12)

It looks like the icon did not upload correctly.
I also tried to look for the website but does not exists ☺️

**Comment by tommycarpi** [comment]
I'll close this issue, feel free to edit with the correct image if you want 👍
