### ISSUE TITLE
Add Icon for Wise

### ISSUE THREAD

**Issue by jj39** [tommycarpi/sentinel-icons#40]
Please add an icon for Wise (formerly TransferWise): https://wise.com/

**Comment by tommycarpi** [comment]
Hello, isn't the current icon already the correct one?

**Comment by jj39** [comment]
![wise](https://user-images.githubusercontent.com/65979251/220430225-2b3a3045-b21b-49a5-acd4-8d0c4d0dd32b.jpg)
There is no current icon, just "Wi"

**Comment by tommycarpi** [comment]
You are right, fixed.
