### ISSUE TITLE
Add icons for Juno.Finance and GA Department of Revenue

### ISSUE THREAD

**Issue by TaoTek** [tommycarpi/sentinel-icons#42]
Please add icons for Juno.Finance and the Georgia Department of Revenue. Here are some examples I've done.
![gadeptofrevenue](https://user-images.githubusercontent.com/48920/235376100-2d16af08-8e50-429d-99e1-1f6e6c174b71.png)
![junofinance](https://user-images.githubusercontent.com/48920/235376101-7cb68c7d-0572-46c1-b22e-1ac51bc4744a.png)

**Comment by tommycarpi** [comment]
Hello Tao,
what issuer are you using for the Georgia Department of Revenue?

**Comment by TaoTek** [comment]
GDR would be fine.  Here is the website https://dor.georgia.gov/ and I'll attach an image that might be a better icon.
 
<img width="200" alt="Georgia_Department_of_Revenue" src="https://user-images.githubusercontent.com/48920/235519245-be4c143b-56cc-419c-9c00-bd9ddfc758f9.png">

**Comment by tommycarpi** [comment]
Added.
