### ISSUE TITLE
Homey

### ISSUE THREAD

**Issue by brakedalen** [tommycarpi/sentinel-icons#47]
Can you please add the Homey logo?
https://www.google.com/url?sa=i&url=https%3A%2F%2Fhomey.app%2F&psig=AOvVaw0mMPpNvtDgKU8V_M1X5z6H&ust=1686899861442000&source=images&cd=vfe&ved=0CBEQjRxqFwoTCLjVh-rdxP8CFQAAAAAdAAAAABAE

**Comment by tommycarpi** [comment]
Done, you can find it under the Issuer "Homey"
