### ISSUE TITLE
Sendy Icon no longer displaying correctly

### ISSUE THREAD

**Issue by abc983ft** [tommycarpi/sentinel-icons#52]
It used to show the correct icon now it shows a green box as shown in the picture below.
https://sendy.co/

![20230727_005429000_iOS](https://github.com/tommycarpi/sentinel-icons/assets/4664989/05bd90dd-617a-4ad2-bbb8-dae0addfbaf9)

**Comment by tommycarpi** [comment]
Hi, icons are automatically displayed based on the "Issuer" field.

From the image above I see the Issuer is blank, only the Account is populated, therefore no icon is correctly displyed.

Try filling the Issuer field 😀 

Cheers

**Comment by abc983ft** [comment]
Thank you, that resolved the issue. However, I’m unsure how the issuer field was removed. It previously displayed the Sendy icon, and I never altered the field. In fact, I wasn’t even aware it could be modified until now. Therefore, it’s probable that an update or a bug may have inadvertently removed the issuer field.

**Comment by tommycarpi** [comment]
Thanks for reporting, I'll investigate the case!
