### ISSUE TITLE
Add unlock app with pin or pattern option in Sentinel settings

### ISSUE THREAD

**Issue by jj39** [tommycarpi/sentinel-icons#59]
You have a Biometric auth permission in the Sentinel settings but you don't have an option to unlock with pin or pattern, please add this as an option for opening the app.

Use case: I installed Sentinel on Windows using Google Play and Android Subsystem for Windows but the biometric authentication setting doesn't do anything (doesn't work with Windows fingerprint reader or Windows Hello) and the app just opens and shows all the 2FA codes. I would like the app to require pin or pattern auth before opening. A Chrome Extension would be a better option for Windows but that is currently not available.

**Comment by tommycarpi** [comment]
Hello, the pin is requested automatically upon failing the biometric auth (either faceID or touchID) or if the biometrics auth is not available/enabled on the device, as per standard.

In your use case I honestly don't know how things are mapped between the Android emulator and the windows OS, do you have any other app that works that way? (Ie passcode works)

Anyway we are planning for both a Chrome extension and Windows app!

**Comment by jj39** [comment]
I guess the reason it didn’t ask for a pin is because I never set up a system wide pin for Android (I didn’t even see an option to do it). I tried a passcode app that pops up and asks for a pin when an app is opened, but clicking the windows notification closes it. I was thinking more of a passcode that is specific to only the app (not one that is set up using the Android operating system which doesn’t seem to be possible on the Windows version of Android). Here is the guide if you are interested: https://youtu.be/5_3hN93vfmE?si=MeRqPL8ltwk2WgMe

Do you have an expected timeframe for a Windows app or Chrome extension? This was more just me playing around with Android for the first time on Windows and I see now that it is not a good solution for secure apps like this given the lack of being able to set a PIN code for Android on Windows.

**Comment by tommycarpi** [comment]
I see!

I don't have an ETA yet, most likely Q1 next year for Chrome and Q2 for Windows.

Cheers

**Comment by jj39** [comment]
Sounds good, closing the issue
