### ISSUE TITLE
New Icon - Ember Fund

### ISSUE THREAD

**Issue by oddlysus** [tommycarpi/sentinel-icons#6]
<img width="200" alt="ember fund" src="https://user-images.githubusercontent.com/111020228/184021100-2b0092a8-b2f9-4fc2-9aa2-b2f4284379e9.png">

Another new icon for app Ember Fund - thank you!

**Comment by tommycarpi** [comment]
Merged, thanks to @IISlapDashII 

Please use the issuer "EmberFund"
