### ISSUE TITLE
Missing an icon

### ISSUE THREAD

**Issue by aandason** [tommycarpi/sentinel-icons#67]
Please add the following icons:
1) Flipper Zero (the dolphin)
2) Finnair

**Comment by tommycarpi** [comment]
Added, use the following "Issuer" names:
- Finnair
- FlipperZero

**Comment by aandason** [comment]
Tom,
I’m unfamiliar with GitHub (not a coder), could you show me an example using screen-recording if I were to submit a new issue, or request an icon next time?
Regards,Ams
  
On Wed, May 1, 2024 at 23:35, tommycarpi ***@***.***&gt; wrote:  Added, use the following "Issuer" names:

Finnair
FlipperZero

**Comment by tommycarpi** [comment]
Hello @aandason, don't worry you can just open an issue here, as you did the first time, with the services you are missing an icon and I'll add them ☺️
Cheers

**Comment by aandason** [comment]
Thanks for adding the Flipper Zero icon promptly, but I’m having another issue, because I attempted to add a little info under the "Issuer", e.g. "Flipper Zero (Forum)", somehow the icon / issuer couldn’t recognise that extra info &amp; the icon was gone again 😂
Ams  
On Wed, May 1, 2024 at 23:43, tommycarpi ***@***.***&gt; wrote:  Hello @aandason, don't worry you can just open an issue here, as you did the first time, with the services you are missing an icon and I'll add them ☺️

Cheers

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you were mentioned.Message ID: ***@***.***&gt;
</blockquote>

**Comment by tommycarpi** [comment]
The icons is found by checking the first part of the issuer before any whitespace (you can see an example [here](https://github.com/tommycarpi/sentinel-icons?tab=readme-ov-file#see-an-example)).

- For Finnair, I'll add Finnair+ so it will show
- For Flipper Zero, just remove the first whitespace "FlipperZero (forum)"
